/*
 * template-spring-boot
 * Description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TemplateSpringBoot) {
      root.TemplateSpringBoot = {};
    }
    root.TemplateSpringBoot.StockItem = factory(root.TemplateSpringBoot.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The StockItem model module.
   * @module model/StockItem
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>StockItem</code>.
   * @alias module:model/StockItem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>StockItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StockItem} obj Optional instance to populate.
   * @return {module:model/StockItem} The populated <code>StockItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = ApiClient.convertToType(data['manufacturer'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('stock'))
        obj.stock = ApiClient.convertToType(data['stock'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} manufacturer
   */
  exports.prototype.manufacturer = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Number} price
   */
  exports.prototype.price = undefined;

  /**
   * @member {Number} stock
   */
  exports.prototype.stock = undefined;


  return exports;

}));
