/*
 * template-spring-boot
 * Description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StockItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/StockItem'));
  } else {
    // Browser globals (root is window)
    if (!root.TemplateSpringBoot) {
      root.TemplateSpringBoot = {};
    }
    root.TemplateSpringBoot.StockItemControllerApi = factory(root.TemplateSpringBoot.ApiClient, root.TemplateSpringBoot.StockItem);
  }
}(this, function(ApiClient, StockItem) {
  'use strict';

  /**
   * StockItemController service.
   * @module api/StockItemControllerApi
   * @version 1.0.0
   */

  /**
   * Constructs a new StockItemControllerApi. 
   * @alias module:api/StockItemControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the listStockItemsUsingGET operation.
     * @callback module:api/StockItemControllerApi~listStockItemsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/StockItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * listStockItems
     * @param {module:api/StockItemControllerApi~listStockItemsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/StockItem>}
     */
    this.listStockItemsUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [StockItem];

      return this.apiClient.callApi(
        '/stock-items', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
