/*
 * template-spring-boot
 * Description
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TemplateSpringBoot);
  }
}(this, function(expect, TemplateSpringBoot) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TemplateSpringBoot.StockItemControllerApi();
  });

  describe('(package)', function() {
    describe('StockItemControllerApi', function() {
      describe('listStockItemsUsingGET', function() {
        it('should call listStockItemsUsingGET successfully', function(done) {
          // TODO: uncomment listStockItemsUsingGET call and complete the assertions
          /*

          instance.listStockItemsUsingGET(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TemplateSpringBoot.StockItem);
              expect(data.id).to.be.a('string');
              expect(data.id).to.be("");
              expect(data.manufacturer).to.be.a('string');
              expect(data.manufacturer).to.be("");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.price).to.be.a('number');
              expect(data.price).to.be(0.0);
              expect(data.stock).to.be.a('number');
              expect(data.stock).to.be(0);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
